name: Run GH Actions CI
on:
  push:
    branches: main
  workflow_dispatch: {}
jobs:
  backend:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "backend/go.mod"
      - name: Install dependencies
        run: go mod download
      - name: Build binary
        run: go build .
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io/SaimonWoidig/gh-actions
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/docker/Dockerfile
          push: true
          tags: ghcr.io/SaimonWoidig/gh-actions/backend:1.0.0
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io/SaimonWoidig/gh-actions
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/docker/Dockerfile
          push: true
          tags: ghcr.io/SaimonWoidig/gh-actions/frontend:1.0.0
